### ISSUE TITLE
Tutorial points to out of date version of api-template

### ISSUE THREAD

**Issue by hally9k** [plugblockchain/api-template#3]
When running through the pl^g tutorial and setting up the node-template and the api-template the tutorial doesn't point to specific tags on the two repos, so the versions are incompatible, resulting in some confusing error messages for beginners. 

At the time of writing the versions conflict and causes the following errors:

Initially without any modification: 
```Connecting to ws://localhost:9944
Unknown signed extensions [OptionSignedExtension] found, treating them as no-efect
Unknown signed extensions [OptionSignedExtension] found, treating them as no-efect
Unknown types found, no types for LastRuntimeUpgradeInfo
You are connected to chain Development using Awesome Node v2.0.0-alpha.5
Alice is transferring 1_500_000_000 to Bob
Error: Error: createType(Call):: Struct: failed on 'args':: Struct: failed on 'value':: Invalid character
    at createTypeUnsafe (/Users/hally9k/Repos/Trackback/api-template/node_modules/@polkadot/types/codec/create/createType.js:68:11)
    at createType (/Users/hally9k/Repos/Trackback/api-template/node_modules/@polkadot/types/codec/create/createType.js:80:10)
    at extrinsicFn (/Users/hally9k/Repos/Trackback/api-template/node_modules/@polkadot/metadata/Decorated/extrinsics/fromMetadata/createUnchecked.js:26:39)
    at Object.decorated [as transfer] (/Users/hally9k/Repos/Trackback/api-template/node_modules/@polkadot/api/base/Decorate.js:208:46)
    at run (/Users/hally9k/Repos/Trackback/api-template/index.js:43:6)
```

Which I assume is complaining about the value format, so I change that line:
```
.transfer(keyring.bob.address, "1_500_000_000")
```
to:
```
.transfer(keyring.bob.address, 1500000000)
```

And then the following error:

```
Connecting to ws://localhost:9944
Unknown signed extensions [OptionSignedExtension] found, treating them as no-efect
Unknown signed extensions [OptionSignedExtension] found, treating them as no-efect
Unknown types found, no types for LastRuntimeUpgradeInfo
You are connected to chain Development using Awesome Node v2.0.0-alpha.5
Alice is transferring 1_500_000_000 to Bob
2020-09-22 15:51:51        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in
Error: Error: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in
    at CatchSubscriber.selector (/Users/hally9k/Repos/Trackback/api-template/node_modules/@polkadot/rpc-core/index.js:195:38)
    at CatchSubscriber.error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/operators/catchError.js:48:31)
    at MapSubscriber.Subscriber._error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SwitchMapSubscriber.OuterSubscriber.notifyError (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/OuterSubscriber.js:26:26)
    at InnerSubscriber._error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/Subscriber.js:72:18)
    at CombineLatestSubscriber.OuterSubscriber.notifyError (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/OuterSubscriber.js:26:26)
    at InnerSubscriber._error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (/Users/hally9k/Repos/Trackback/api-template/node_modules/rxjs/internal/Subscriber.js:72:18)
```

**Comment by hally9k** [comment]
Attempts to match the versions to 1.0.0-rc4 here: https://github.com/plugblockchain/api-template/issues/4

**Comment by jordy25519** [comment]
I've updated the wiki to use
```
.transfer(keyring.bob.address, 1500000000)
```
and to use a specific plug node version in getting started

**Comment by jordy25519** [comment]
Wiki updated so I think this can be closed now. Will re-open if any further issues

**Comment by hally9k** [comment]
@holygits Suggestion, change that line to
```
.transfer(keyring.bob.address, BigInt("1500000000000000"))
```
As the current transaction is too small to show up on the polkadot/apps dashboard based on my little experiment there.
